var layer_OpenRailwayMap_1 = L.tileLayer(
    'https://a.tiles.openrailwaymap.org/standard/{z}/{x}/{y}.png',
    {
      pane: 'pane_OpenRailwayMap_1',
      opacity: 1.0,
      attribution: '',
      minZoom: 6,
      maxZoom: 24,
      minNativeZoom: 0,
      maxNativeZoom: 18,
      center: [51.351, 10.454],
      bounds: null,
      lines: null,
      polylines: null,
      polyline_options: {
        opacity: 0.75,
        opacity2: 0.75,
        opacity0: 0,
        opacity_over: 0.1,
        weight: 3,
        weight3: 3,
        weight20: 20,
        color: '#003472',
        color_red: '#F01414',
      },
      polygon_options: {
        color: '#f39200',
        weight: 1,
      },
      map: null,
      allprojects: null,
      categories: null,
      selectedCategories: [],
      latestprojects: null,
      showLatest: !0,
      searchword: '',
      keywords: [],
      projectslist: null,
      allprojectslist: null,
      showProjectsList: !0,
      ptHeaders: [
        {
          text: 'Bauprojekt',
          align: 'start',
          value: 'shorttitle',
        },
      ],
      in_update: 0,
      iconSize: 42,
      clusterOptions: {
        showCoverageOnHover: !1,
      },
      geojson: null,
      optionsStyle: {
        color: '#aaa',
        fillOpacity: 0.6,
      },
      popupOptions: {
        class: 'projectPopup',
      },
      overlay: !0,
      isAutocompleteLoading: !1,
      loadKeywords: null,
      awaitingSearch: !1,
      currentView: 'map',
      filterClass: '',
      slickSettings: {
        dots: !0,
        centerMode: !0,
        centerPadding: '20px',
        focusOnSelect: !1,
        infinite: !0,
        initialSlide: 0,
        slidesToShow: 1,
        slidesToScroll: 1,
        variableWidth: !0,
        speed: 400,
        autoplaySpeed: 3e3,
        arrows: !0,
        autoplay: !1,
        touchMove: !0,
      },
      slider: !1,
      selectedItem: null,
      beforeTxt: 1,
    }
  );